# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

# 영어 메뉴
main:
  - name: "About"
    url: /en/
    weight: 10
  - name: "Papers"
    url: /en/#papers
    weight: 11
  - name: "Talks"
    url: /en/#talks
    weight: 12
  - name: "News"
    url: /en/#news
    weight: 13
  - name: "Experience"
    url: /en/experience/
    weight: 20
  - name: "Projects"
    url: /en/projects/
    weight: 30
  # - name: "Teaching"
  #   url: /en/teaching/
  #   weight: 40